name: flixmovix
description: "A flutter mobile application for movies and TV shows."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.1


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8
  beautiful_soup_dart: ^0.3.0
  flutter_dotenv: ^5.2.1
  flutter_inappwebview: ^6.1.5
  http: ^1.4.0
  get: ^4.7.2
  internet_connection_checker: ^3.0.1
  dashed_circular_progress_bar: ^0.0.6
  shared_preferences: ^2.5.3
  flutter_spinkit: ^5.2.1
  flutter_svg: ^2.2.0
  flutter_launcher_icons: ^0.14.4
  unity_ads_plugin: ^0.3.25
  infinite_scroll_pagination: ^5.1.0
  firebase_core: ^3.14.0
  cloud_firestore: ^5.6.9
  url_launcher: ^6.3.1
  flutter_native_splash: ^2.4.4
  webview_flutter: ^4.13.0
  rename: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^5.0.0


flutter:

  uses-material-design: true

  assets:
    - .env
    - assets/images/
    - assets/svg/


  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #

